data_cfg:
  dataset_name: Gait3D
  # dataset_root: original_gait_3d_for_test/Gait3D-sils-64-44-pkl  # original dataset for inference
  dataset_root: gait3d_with_cluster_view_label/Gait3D-sils-64-44-pkl_view_order #  training dataset
  num_workers: 1
  dataset_partition: ./datasets/Gait3D/Gait3D.json
  remove_no_gallery: false
  cache: false
  test_dataset_name: Gait3D

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 50000
  save_name: GaitCSV
  eval_func: evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 8
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos euc
  transform:
    - type: BaseSilTransform

model_cfg:
  model: GaitCSV
  backbone_cfg:
    block: BasicBlock
    channels: # Layers configuration for automatically model construction
      - 64
      - 128
      - 256
      - 512
    layers:
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
    type: ResNet9

  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 3000
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    view_num: 14
    type: CIML
    log_prefix: CIML
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true
    label_smooth: false

  
optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 20000
    - 30000
    - 40000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: false
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: GaitCSV
  sync_BN: true
  total_iter: 50000
  sampler:
    batch_shuffle: true
    batch_size:
      - 14 # V cluster number
      - 4  # P
      - 4  # K
    frames_num_fixed: 30 # 16
    frames_skip_num: 0
    sample_type: unfixed_unordered # order
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 10 # min frames number for unfixed traing
    # sample_type: fixed_ordered
    type: ViewTripletSampler
  transform:
    # - img_w: 64
    #   type: BaseSilTransform
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2
        - type: BaseSilTransform
